services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: registros_usuarios
    ports:
      - "3306:3307"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi_backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: dash_frontend
    ports:
      - "8050:8050"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

volumes:
  mysql_data: